Rira 7.adjustment to many services and tests
GRISERA/grisera-framework pull request #121
Opened 2022-11-30 16:42 UTC by migowskiD

Implementation of dependency injection. The idea is to allow creating router with the specific service class. Each class which can be a parameter for router constructor class should be of the same type (should inherit from the same class). For each set of service classes, which are used to create routers there is defined a seperate configuration, which is given as a variable in docker-compose.yml.

2022-12-01 11:02 UTC, mrwrob requested changes
It looks really good :+1: 
All tests in  `tests/tests_*` directories refer now to the GraphDB backend. Therefore, I suggest to create new subdirectory inside `tests/`, lets called id `tests_graphdb`, and move all the `tests_*` directories  there.

Please address all other comments and we can marge it :smile:

2022-12-01 18:57 UTC, mrwrob requested changes

2022-12-01 18:57 UTC, mrwrob commented on grisera_api/services.py
> +            return ActivityServiceGraphDB
Not that way :facepalm: I though that my comment was pretty clear... You should add parentheses, not remove them...
```python
    def activity_service(self) -> ActivityService:
        if self.persistence_type == PersistenceTypes.GRAPHDB:
            return ActivityServiceGraphDB()
        else:
            return ActivityService()
```

2022-12-04 12:07 UTC, mrwrob approved these changes
Good work!

2022-12-05 17:47 UTC, Kajeszuk approved these changes
Great code!

2022-12-05 17:56 UTC, merged