ON-5/implementation add instance function
GRISERA/grisera-framework pull request #126
Opened 2022-12-04 19:05 UTC by pankogito

ON-5
implementation and tests for add instance function

2022-12-06 09:14 UTC, mrwrob requested changes
Please don't forget to reformat the code (Ctrl+Alt+L in PyCharn)

2022-12-06 09:14 UTC, mrwrob commented on ontology_api/model/model_service.py
>  from owlready2 import get_ontology
Please reformat code (Ctrl+Alt+L in PyCharm)

2022-12-06 09:14 UTC, mrwrob commented on ontology_api/model/model_service.py
> +    def add_instance(self, class_id, model_id, model_in: MinimalInstanceModelIn):
Please add description of this function. I don't get what this is supposed to do.... What class the `model` is? Does it have `classes` method? What is the result of this function? Is it setting something, or returning?

2022-12-06 09:14 UTC, mrwrob commented on ontology_api/tests/test_model_router.py
> +        background_tasks = BackgroundTasks()
Are we using this variable?

2022-12-18 16:43 UTC, PLangowski approved these changes
Looks good

2023-01-31 09:50 UTC, mrwrob approved these changes
LGTM :+1:

2023-01-31 09:53 UTC, merged