ON-17 Added a database to Ontology API
GRISERA/grisera-framework pull request #134
Opened 2023-01-02 20:07 UTC by PLangowski

2023-01-03 12:55 UTC, mrwrob requested changes
Seems fine, please optimize imports.

2023-01-03 12:55 UTC, mrwrob commented on ontology_api/model/model_router.py
> +    async def get_owl(self, id: int, response: Response):
When you removed `BackgroundTasks`, please remove relevant import as well.

2023-01-03 12:55 UTC, mrwrob commented on ontology_api/tests/test_model_router.py
> +        model = get_ontology("http://www.semanticweb.org/GRISERA/contextualOntology")
Check unused imports.

2023-01-04 18:25 UTC, mrwrob approved these changes
Seems fine :+1:

2023-01-04 18:33 UTC, KKucht approved these changes
I believe in this man

2023-01-04 18:34 UTC, merged