ON-25: Ontology API get_instance method
GRISERA/grisera-framework pull request #146
Opened 2023-03-03 11:24 UTC by PLangowski

2023-03-03 15:03 UTC, pankogito approved these changes

2023-03-07 13:45 UTC, mrwrob requested changes
Seems legit, just remove obsolete import.

2023-03-07 13:45 UTC, mrwrob commented on ontology_api/instance/instance_service.py
>  from fastapi import UploadFile
I think this import is no longer needed

2023-03-07 14:57 UTC, PLangowski commented on ontology_api/instance/instance_service.py
>  from fastapi import UploadFile
done

2023-03-07 20:09 UTC, mrwrob approved these changes

2023-03-07 21:09 UTC, merged