Rira 13.managing datasets
GRISERA/grisera-framework pull request #158
Opened 2023-03-11 19:08 UTC by theNIGHTMAR3

Done:
-Managing Datasets
-Define database connection
-Create dataset function
-Rework services classes
-Getters and setter for dataset
-Manage connection Neo4J
-Unit tests

2023-03-15 17:11 UTC, KrzysztofNazar01 commented
@mrwrob 
Should we solve the conflicts between the branches and then create a new PR?

2023-03-18 19:06 UTC, mrwrob commented
@KrzysztofNazar01, no need for new PR. Just rebase, resolve conflicts and push commit. If it's in the same branch, it will appear in this PR.

2023-03-26 18:34 UTC, mrwrob requested changes
I think we should add default value (`neo4j` I think) for  `database_name` in all routers in  `grisera_api`. Otherwise we'll break backward compatibility.  

If you want to log some issue on the console, you should not use prints: https://climbtheladder.com/8-fastapi-logging-best-practices/

2023-03-26 18:34 UTC, mrwrob commented on graph_api/node/node_router.py
> +        create_response = self.node_service.save_node(node, database_name)
Is it some debugging artefact?

2023-03-26 18:34 UTC, mrwrob commented on graph_api/database_service.py
> +        print("response in post_statement: ", response)
Is it needed here?

2023-03-26 18:34 UTC, mrwrob commented on grisera_api/graph_api_service.py
> +        #     response_data = {}
What's about these comments?

2023-03-26 18:34 UTC, mrwrob commented on graph_api/dataset/dataset_router.py
> +        database_name = "neo4j"
Should the database name be passed through the call?

2023-03-27 08:21 UTC, closed without merging