ON-7: Add Property Role
GRISERA/grisera-framework pull request #161
Opened 2023-03-12 15:34 UTC by KKucht

2023-03-14 19:12 UTC, mrwrob requested changes
Please refactor `RoleService` class to remove `exec` call

2023-03-14 19:12 UTC, mrwrob commented on ontology_api/role/role_service.py
> +        exec(code)
I don't like this code at all. 
What is the `src_instance`? Is it a class? A dict? If it's a class you can probably use `getattr`... 
`exec` is almost never a good idea...

2023-03-16 19:22 UTC, PLangowski approved these changes
Nice!

2023-03-18 19:11 UTC, mrwrob commented
It's much better now!

2023-03-18 19:12 UTC, mrwrob approved these changes
It's much better now :+1:

2023-03-19 16:42 UTC, merged