delete instance
GRISERA/grisera-framework pull request #164
Opened 2023-03-27 08:52 UTC by pankogito

implementation of delete function instance

2023-03-27 11:13 UTC, KKucht requested changes
Change pull name to ON-33: Delete instance

2023-03-27 11:13 UTC, KKucht commented on ontology_api/instance/instance_service.py
> +                return FullInstanceModelOut(instance_id=instance_id, label=instance_label)
I don't see update ontology

2023-03-27 11:13 UTC, KKucht commented on ontology_api/instance/instance_service.py
> +            errors="Instance with label " + str(instance_label) + " not found in Model " + str(model_id))
It better looks, if the correct model is in the end.

2023-03-31 11:42 UTC, KKucht approved these changes

2023-05-23 10:40 UTC, mrwrob requested changes

2023-05-23 13:59 UTC, PLangowski commented on ontology_api/instance/instance_service.py
> +    def delete_instance(self,model_id: int, class_name: str, instance_label: str):
@mrwrob Fixed.

2023-05-25 07:28 UTC, mrwrob approved these changes
Good job :+1:

2023-05-27 14:15 UTC, merged